### ISSUE TITLE
Null Safety Migration

### ISSUE THREAD

**Issue by Arcturus5404** [avioli/uni_links#103]
Is there any change this library getting null safety support?

**Comment by orevial** [comment]
This library is actually already null safe, I think the only thing for Flutter/Dart to recognize it is to migrate to Flutter 2, which I've proposed in PR #104

**Comment by Arcturus5404** [comment]
Awesome!

**Comment by miDeb** [comment]
Well, the only missing thing is to push a new version to pub.dev. @avioli could you take care of that?

**Comment by higorlapacw** [comment]
Any news on the push?

**Comment by objectivecosta** [comment]
Bump!

**Comment by psrcek** [comment]
hello???

**Comment by objectivecosta** [comment]
I don't know if @avioli is alright or just took some time off, either way, I made a simplified version for personal usage while the lib is not updated!

https://github.com/objectivecosta/uni_links_simplified

Hope everything is all right!

**Comment by Arcturus5404** [comment]
@objectivecosta Is this a nullsafe variant of this lib?

**Comment by Arcturus5404** [comment]
@orevial maybe you should push a version to pub.dev too, call it flutter_uni_links

**Comment by BringTheChill** [comment]
@objectivecosta I agree with @Arcturus5404 . Can you do this?

**Comment by objectivecosta** [comment]
@Arcturus5404 @BringTheChill pushing another version of the lib is not the solution. I made a simplified repo which you can use to develop ATM, just add it as a git dependency on the pubspec.yaml. Pushing to pub.dev just so a few more lines on the pubspec could be saved is not a good solution.

Let's just wait for @avioli.

**Comment by BringTheChill** [comment]
@objectivecosta thank you anyway for your effort with this. you helped me a lot!

**Comment by objectivecosta** [comment]
If anyone else need temporary help running this:

```
# uni_links: ^0.4.0
  uni_links:
    git:
      url: git@github.com:objectivecosta/uni_links_simplified.git
```

DISCLAIMER: You'll be running the simplified version I put in https://github.com/objectivecosta/uni_links_simplified

**Comment by orevial** [comment]
I agree, forking the plugin to `pub.dev` is not a good solution as it will imply that the two packages will forever live side-by-side and efforts to maintain one of the other are duplicated which is not good IMHO.

I'd rather wait for @avioli to hopefully come back and in the mean time we can all depend on a Git branch for a null-safe version of the plugin 😉

**Comment by Arcturus5404** [comment]
@objectivecosta Can you explain what the simplified means? What did you remove for instance?

**Comment by Arcturus5404** [comment]
If you changed too much, a better solution for now would be:

```
uni_links: ^0.4.0
  uni_links:
    git:
      url: git@github.com:orevial/uni_links/tree/null-safety-migration
```

**Comment by objectivecosta** [comment]
@Arcturus5404 uni_links depends on pub.dev's uni_links_web, which is not published yet. I just put it all in one package.

**Comment by cbenhagen** [comment]
You need to override all three packages:
```yaml
  uni_links:
    git:
      url: git@github.com:orevial/uni_links
      ref: null-safety-migration
      path: uni_links
  uni_links_platform_interface:
    git:
      url: git@github.com:orevial/uni_links
      ref: null-safety-migration
      path: uni_links_platform_interface
  uni_links_web:
    git:
      url: git@github.com:orevial/uni_links
      ref: null-safety-migration
      path: uni_links_web
```

**Comment by orevial** [comment]
> You need to override all three packages:
> 
> ```yaml
>   uni_links:
>     git:
>       url: git@github.com:orevial/uni_links
>       ref: null-safety-migration
>       path: uni_links
>   uni_links_platform_interface:
>     git:
>       url: git@github.com:orevial/uni_links
>       ref: null-safety-migration
>       path: uni_links_platform_interface
>   uni_links_web:
>     git:
>       url: git@github.com:orevial/uni_links
>       ref: null-safety-migration
>       path: uni_links_web
> ```

Not really, it won't work as I kept local versions dependencies (the author needs to update the platform interface first and then upgrade `uni_links_web`and `uni_links` dependecy version to `uni_links_platform_interface`). With your solution you will probably get an error such as this one:

```

Because every version of uni_links_web from git depends on uni_links_platform_interface from hosted and YOUR-APP depends on uni_links_platform_interface from git, uni_links_web from git is forbidden.
```

In the meantime I created another branch with the same code but where `uni-links-*` dependencies are pointing to the same Git repository so each dependecy can be resolved. To use it:

```yaml
uni_links:
    git:
      url: git@github.com:orevial/uni_links
      ref: null-safety-migration-local-git-repo
      path: uni_links
```

Note that this way you don't need to depend on inner packages (web/platform_interface)
